### PR TITLE
Fix compatibility with modern lift

### PR DESCRIPTION
**Pull request by catap**

### CODE REVIEW

**Comment by hraban** [comment]
Hi I force pushed history from gitlab.common-lisp.net but I haven't forgotten about this thanks for the PR

**Comment by catap** [comment]
Have you merged it or shall I recreate it?

**Comment by hraban** [comment]
Don't worry I will cherry-pick from this PR

**Comment by hraban** [comment]
Thank you, fixed and pushed. 👍

**Comment by hraban** [comment]
@catap come to think of it, isn't it kinda weird that lift broke backwards compatibility in this way? I don't really see the point in this change... can't it just detect a slash / directory name in the name and do what it needs to, itself?

I recently took over maintenance of lift and I'm tempted to fix this upstream rather than in every dependent package such as cl-markdown.

Wdy think?

**Comment by catap** [comment]
Well.. it required to hack lift and I've backported a few similar patches across lisp world for last couple of months O:-)...

**Pull request closed without merging**
